export interface Product{
  id:number,
  imgs:string[],
  img:string,
  title:string,
  price:number,
  colors:string[],
  color:string,
  sizes:string[],
  size:string,
  inStock:boolean,
  stock:number,
  categories:string[],
  description:string,
  details:string,
  hasDiscount:boolean,
  discount:number,
  rating:number[]
};
